
module.exports = {
  NOM_EMPRESA: "KÄRŸ",
  SCRIPT_BASE_URL: "", // Aquesta variable ja no és necessària a Firebase
  SHEET_NEW_USERS: "-NEW USERS-",
  SHEET_REG_USERS: "-REG USERS-",
  Dashboard: "Dashboard",
  Login: "Login",
  Admin: "Admin",
  Newuser: "Newuser",
  AF_GALLINA: "AF_GALLINA",
  AF_CLIENTS: "AF_CLIENTS",
  PAG_INDEF: "PAG_INDEF",
  PAG_0: "PAG_0",
  EMAIL_COLUMN: 2,
  PASSWORD_COLUMN: 20,
  NEW_USERS_COLS: {
    ID: 1,
    EMAIL: 2,
    NOM: 3,
    COGNOMS: 4,
    DNI: 5,
    ADRECA: 6,
    POBLACIO: 7,
    PAIS: 8,
    CODI_POSTAL: 9,
    DATA_SOLLICITUD: 10,
    TELEFON: 11,
  },
  REG_USERS_COLS: {
    ID_REGISTRE: 1,
    EMAIL: 2,
    URL_SHEET: 3,
    NOM: 4,
    COGNOMS: 5,
    TELEFON: 6,
    DNI: 7,
    ADRECA: 8,
    POBLACIO: 9,
    PAIS: 10,
    CODI_POSTAL: 11,
    ID_USER_ORIGINAL: 12,
    DATA_SOLLICITUD: 13,
    DATA_REGISTRE: 14,
    REGISTRAT: 15,
    DATA_COBRAMENT: 16,
    METODE_PAGAMENT: 17,
    COBRAT: 18,
    QUANTITAT_PAGADA: 19,
  },
};
